### ISSUE TITLE
Can't compile orcania.c ( e47c7ba commit )

### ISSUE THREAD

**Issue by diegozzo** [babelouest/orcania#1]
Hi, 
very usefull  project.
Following your guide, I was trying to compile the ulfius project after I downloaded the submodules.
( e47c7ba commit )

gcc gave me the following error:
`orcania.c: In function ‘json_search’:
orcania.c:234:5: warning: implicit declaration of function ‘json_array_foreach’ [-Wimplicit-function-declaration]
orcania.c:234:49: error: expected ‘;’ before ‘{’ token
`
Any issue?

Thank you,
Diego

**Comment by babelouest** [comment]
Hi,

You need `jansson` devlopment files to compile orcania. There is no README file for Orcania since it's a satellite library used with some other libraries and program I made, but I will update that soon.

For example, if you use a debian based distribution, run the command:

``` shell
$ sudo apt-get install libjansson-dev
```

Or you can install jansson directly from the source: http://www.digip.org/jansson/
